Обновил 5 спринт
ArtemP878/MovieQuiz-ios pull request #5
Opened 2023-02-12 21:37 UTC by ArtemP878

Скорректировал 5 спринт

2023-02-12 21:38 UTC, ArtemP878 commented
Надеюсь теперь будет норм

2023-02-13 07:50 UTC, protos17 requested changes

2023-02-13 07:50 UTC, protos17 commented on MovieQuiz/Presentation/AlertPresenter/AlertPresenter.swift
> +import Foundation
При импортировании UIKit, не нужно имортировать Foundation, т.к. UIKit в себе уже содержит Foundation

2023-02-13 07:50 UTC, protos17 commented on MovieQuiz/Presentation/AlertPresenter/AlertPresenter.swift
> +class AlertPresenter: AlertPresenterProtocol {
Хочу отметить, что класс без наследования стоит указать как final, материал, почему нужно это нужно сделать оставлю в рекомендациях

2023-02-13 07:50 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        print(NSHomeDirectory())
Хочу отметить, что после того, как завершил работу в ветке стоит удалить все принты для отладки

2023-02-13 07:50 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
>          DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
Retain cycle, необходимо добавить [weak self] in

2023-02-13 07:50 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            let action: (UIAlertAction) -> Void = { _ in
Retain cycle, необходимо добавить [weak self] in

2023-02-13 07:50 UTC, protos17 commented on MovieQuiz/Models/AlertModel.swift
> +import Foundation
При импортировании UIKit, не нужно имортировать Foundation, т.к. UIKit в себе уже содержит Foundation

2023-02-13 07:50 UTC, protos17 commented on MovieQuiz/Models/QuizStepViewModel.swift
> +import Foundation
При импортировании UIKit, не нужно имортировать Foundation, т.к. UIKit в себе уже содержит Foundation и можно удалить лишние отступы

2023-02-13 07:50 UTC, protos17 commented on MovieQuiz/Presentation/AlertPresenter/AlertPresenter.swift
> +
Советую поудалять лишние отступы

2023-02-13 07:50 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +
Здесь стоит удалить лишний отступ

2023-02-13 07:50 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            let text = "Ваш результат: \(correctAnswers) из \(questionsAmount)\nКоличество сыгранных квизов: \(statisticService.gamesCount)\nРекорд: \(bestGame.correct)/\(bestGame.total) (\(bestGame.
Можно использовать многострочный литерал, материал оставил в комментариях

2023-02-13 07:50 UTC, protos17 commented on MovieQuiz/Services/QuestionFactory.swift
> +class QuestionFactory: QuestionFactoryProtocol {
Класс без наследования, стоит пометить как final

2023-02-13 07:50 UTC, protos17 commented on MovieQuiz/Services/QuestionFactory.swift
> +                     text: "Рейтинг этого фильма больше чем 6?",
Постоянно дублирующуюся строку лучше вынести в отдельную переменную

2023-02-13 07:50 UTC, protos17 commented on MovieQuiz/Services/StatisticService.swift
> +                print("Невозможно сохранить результат")
Для отлова ошибки вместо print лучше использовать assertionFailure

2023-02-13 20:41 UTC, closed without merging